#!/bin/bash

MODULE=`python -c 'import proxapy; import os.path; print(os.path.dirname(os.path.realpath(proxapy.__file__)))'`
APP_PATH=${MODULE%/*}
APP_MODULE='proxapy.proxapy:app'
CONFIG_FILE="$APP_PATH/proxapy/config.py"

gunicorn -c $CONFIG_FILE --pythonpath $APP_PATH $APP_MODULE
